apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-datos
  labels:
    app.kubernetes.io/name: mariadb
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi
