apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ideas-creativas-api-datos
  labels:
    app.kubernetes.io/name: ideas-creativas-api
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 256Mi
